/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentValue } from './documentValue';


export interface CreateDocumentRequest { 
    /**
     * The user ID the document is for.
     */
    recipientId: string;
    /**
     * Key-value pairs to be used in the document.
     */
    documentValues: Array<DocumentValue>;
    /**
     * Amount of days the document will be valid for since the date of its creation. Only required if template type is Lease.
     */
    expiresIn?: number;
}

