/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentSignatureResponse } from './documentSignatureResponse';


export interface CreateDocumentSignature200Response { 
    data?: Array<DocumentSignatureResponse>;
    success?: boolean;
    error?: object;
}

