/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentResponse } from './documentResponse';


export interface CreateDocument200Response { 
    data?: Array<DocumentResponse>;
    success?: boolean;
    error?: object;
}

