/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTemplateRequest { 
    /**
     * Name of your template
     */
    templateName: string;
    /**
     * Description of your template
     */
    templateDescription: string;
    /**
     * Encoded HTML
     */
    markup: string;
    /**
     * The template type. -  1 = lease, 2 = confirmation, 3 = information, 4 = insurance
     */
    templateTypeId: number;
}

