/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentValue } from './documentValue';


export interface DocumentResponse { 
    /**
     * Document Id
     */
    documentId: string;
    /**
     * The user ID the document is for.
     */
    recipientId: string;
    /**
     * Id of the template
     */
    templateVersionId: string;
    /**
     * Current document status
     */
    documentStatusId: number;
    /**
     * Current document condition
     */
    documentConditionId: number;
    /**
     * Key-value pairs to be used in the document.
     */
    documentValues: Array<DocumentValue>;
    /**
     * Expires At
     */
    expiresAt?: string;
    /**
     * Template type
     */
    templateTypeId: DocumentResponse.TemplateTypeIdEnum;
    /**
     * Pre signed url to download the document
     */
    downloadUrl: string;
    /**
     * Created At
     */
    createdAt: string | null;
    /**
     * Updated At
     */
    updatedAt?: string | null;
    /**
     * Encoded HTML
     */
    markup: string;
}
export namespace DocumentResponse {
    export type TemplateTypeIdEnum = 1 | 2 | 3 | 4;
    export const TemplateTypeIdEnum = {
        NUMBER_1: 1 as TemplateTypeIdEnum,
        NUMBER_2: 2 as TemplateTypeIdEnum,
        NUMBER_3: 3 as TemplateTypeIdEnum,
        NUMBER_4: 4 as TemplateTypeIdEnum
    };
}


