/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentSignatureResponse { 
    /**
     * Document signature Id
     */
    documentSignatureId: string;
    /**
     * The id of the person who has signed.
     */
    signeeId: string;
    /**
     * The type of signee; 1 = user, 2 = contact
     */
    signeeType?: number;
}

