/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetTemplates200ResponseDataInner } from './getTemplates200ResponseDataInner';


export interface GetTemplates200Response { 
    data?: Array<GetTemplates200ResponseDataInner>;
    success?: boolean;
    error?: object;
}

