/**
 * ManageSpace Documents API
 * ManageSpace Documents API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TemplateResponse { 
    /**
     * Template Id
     */
    templateId: string;
    /**
     * Template Name
     */
    templateName: string;
    /**
     * Template Description
     */
    templateDescription: string;
    /**
     * Id of the template
     */
    templateVersionId: string;
    /**
     * The Version of the template.
     */
    templateVersion: number;
    /**
     * Encoded HTML
     */
    markup: string;
    /**
     * The Version of the template.
     */
    templateTypeId: number;
}

